[project]
name = "bise"
version = "0.1.0"
description = "A bot to fill BISEMpk forms"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "openpyxl>=3.1.5",
    "pandas>=2.3.2",
    "playwright>=1.55.0",
    "streamlit>=1.49.1",
]
